name: Runtimes Install With Specialized Containers
run-name: Runtimes Install ğŸ³ğŸš€
on: [push]
jobs:
   Install-Go:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.0-alpine3.19
    steps:
      - run: go version
   Install-NodeJS:
    runs-on: ubuntu-latest
    container:
      image: node:21.6.2-slim
    steps:
      - run: node --version

